[WIP] Initial draft
PumasAI-Labs/Data-Visualization pull request #1
Opened 2023-06-29 16:23 UTC by jotas6

# Status

- [ ] Remove PLACEHOLDER text
- [x] Update README file
- [ ] Code examples
- [ ] Add content to home page
- [ ] Reference sheet
- [ ] Instructor notes
- [ ] Schedule

2023-08-01 18:56 UTC, storopoli commented
I think that in this one we should break tradition and insert the `ggplot` vs `AoG.jl` table (https://tutorials.pumas.ai/html/PlottingInJulia/01-AoG-intro.html) in the `reference.md`.

2023-08-01 19:15 UTC, storopoli requested changes
Some suggestions.

2023-08-01 19:15 UTC, storopoli commented on docs/instructors.md
```suggestion

It is a good starting point to ask if learners have experience with the "grammar of graphics" plotting approach.
This could be either from R's `ggplot2` or Python's `plotnine`.
Building upon users previous experiences is highly advisable in this workshop.
If your experience intersects with the learner's experience,
use analogies between these and `AoG.jl` (short for `AlgebraOfGraphics.jl`) whenever possible.
In the specific case of `ggplot2`, you can refer learners to the `ggplot2` versus `AoG.jl` comparison table in the reference sheets.
```

2023-08-01 19:15 UTC, storopoli commented on docs/instructors.md
And add the table in `reference.md`

2023-08-01 19:15 UTC, storopoli commented on docs/instructors.md
> +inform `AoG.jl` (short for `AlgebraOfGraphics.jl`) about the data source for the plot. After that, explain `mapping`, which is in charge of defining how that data
```suggestion
inform `AoG.jl` about the data source for the plot. After that, explain `mapping`, which is in charge of defining how that data 
```

2023-08-01 19:15 UTC, storopoli commented on docs/instructors.md
> +bar plot that shows the mean values of a variable. It may also be helpful to explain the `histogram` function, which, as the name suggests, facilitates the creation of histograms. Emphasize how using
Aren't you gonna mention the collision between `AoG` and `CairoMakie` for the `histogram` and `density` functions?

2023-08-01 19:15 UTC, storopoli commented on docs/instructors.md
> +introduce the `linear` and `smooth` built-in functions, which allow plotting a linear regression and a smoothing line, respectively.
Also I think that `linear` has a collision with `Pumas.jl` if I am not mistaken.

2023-08-01 19:15 UTC, storopoli commented on docs/reference.md
>  ## Glossary
Include:

- [ ] Cairo (and `CairoMakie.jl`)
- [ ] OpenGL (and `GLMakie.jl`)
- [ ] Facets and Layouts

Expand `Makie.jl`

2023-08-01 19:15 UTC, storopoli commented on 01-layers.jl
> +data_layer = data(demographics_df) # data(<DataFrame>)
Maybe a `typeof` to show that it is a `Layer` type. Or will that confuse even more the users?

2023-08-01 19:15 UTC, storopoli commented on 01-layers.jl
> +# Save and download the plot
This is missing

2023-08-01 19:15 UTC, storopoli commented on 03-geometries.jl
> +    AlgebraOfGraphics.expectation() |> draw # Both Pumas and AlgebraOfGraphics export expectation
Include in the instructor's note.

2023-08-01 19:15 UTC, storopoli commented on 04-algebra.jl
> +    (visual(Scatter) + AlgebraOfGraphics.linear() + smooth()) |> draw
Say that Pumas an AoG collide on `linear`

2023-08-01 20:04 UTC, jotas6 commented
> I think that in this one we should break tradition and insert the `ggplot` vs `AoG.jl` table (https://tutorials.pumas.ai/html/PlottingInJulia/01-AoG-intro.html) in the `reference.md`.
> 
> Edit: and also make analogies, I can help you with that...

Of course, I can add that table. Would this be a replacement for the summary of basic commands or something that would be added in addition?

2023-08-01 20:07 UTC, jotas6 commented on docs/instructors.md
> +bar plot that shows the mean values of a variable. It may also be helpful to explain the `histogram` function, which, as the name suggests, facilitates the creation of histograms. Emphasize how using
Thank you. I wasn't sure if that would be too much detail, but thinking again that is something that users will have to take into account every time that they use the functions, so I will add the notes for all the cases that apply (also for the Pumas collisions)

2023-08-01 20:13 UTC, jotas6 commented on 01-layers.jl
> +# Save and download the plot
I left it there as an indication to the instructor to showcase how to save and download plots using the plot navigator, so that would be done once the plot pops up in JuliaHub.

I can see how this comment could be confusing. Would something like `Save and download the plot using the plot navigator` be better? I also considered covering the `save` function from `Makie.jl`, but thought that most users would want to use the plot navigator instead.

2023-08-01 20:23 UTC, jotas6 commented on docs/reference.md
>  ## Glossary
I have a small explanation about faceting. Should I expand it?

![image](https://github.com/PumasAI-Labs/Data-Visualization/assets/80299581/d6f39295-1756-4975-9a6d-e5e80a3f4107)

2023-08-02 11:55 UTC, storopoli commented on docs/reference.md
>  ## Glossary
No, I don't think so. I might have missed it sorry.

2023-08-02 11:56 UTC, storopoli commented on 01-layers.jl
> +# Save and download the plot
Yes, let's cover the `save` function. I think it is important, specially the `[pt|px]_per_unit` kwarg.

2023-08-02 11:57 UTC, storopoli commented
> > I think that in this one we should break tradition and insert the `ggplot` vs `AoG.jl` table (https://tutorials.pumas.ai/html/PlottingInJulia/01-AoG-intro.html) in the `reference.md`.
> > Edit: and also make analogies, I can help you with that...
> 
> Of course, I can add that table. Would this be a replacement for the summary of basic commands or something that would be included in addition?

Addition. Don't replace the summary of basic commands.

2023-08-02 12:03 UTC, jotas6 commented on docs/reference.md
>  ## Glossary
No problem

2023-08-02 18:49 UTC, jotas6 commented
I think I have covered all the comments. We would still need to add the analogies to `ggplot2`, but I am not sure where to begin or where it is relevant to add them.

2023-08-03 16:46 UTC, storopoli commented
> I think I have covered all the comments. We would still need to add the analogies to `ggplot2`, but I am not sure where to begin or where it is relevant to add them.

Let's keep just the table now. We can add later if necessary.

2023-08-03 16:49 UTC, storopoli requested changes
One minor thing

2023-08-03 16:49 UTC, storopoli commented on docs/reference.md
> +Graphics** concept and is similar to R's `ggplot2`.
Add this citation to the Grammar of Graphics: https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448

2023-08-03 16:50 UTC, jotas6 commented on docs/reference.md
> +Graphics** concept and is similar to R's `ggplot2`.
Great, thank you. Would adding a link be okay or should I have a formal citation to the book?

2023-08-03 20:17 UTC, storopoli approved these changes

2023-08-03 20:35 UTC, merged